// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qajnfujinlwashzzatbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFham5mdWppbmx3YXNoenphdGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjczMjMsImV4cCI6MjA2OTQ0MzMyM30.TxDS3y71NMfYp0_yt-KFIg-PixbmMpe-gHhxxStkEjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});